# Generated by Django 4.2.1 on 2023-06-06 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Likes',
            field=models.ManyToManyField(related_name='mag_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
