# Generated by Django 4.2.1 on 2023-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0007_topic_alter_comment_options_article_topic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
    ]
