# Generated by Django 4.2.1 on 2023-06-25 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0009_alter_article_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
