# Generated by Django 4.2.1 on 2023-07-23 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0010_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="favourites",
            field=models.ManyToManyField(
                related_name="favourite_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
